name: Pull Request Checks

on:
  pull_request:
    branches:
      - develop
      - main

permissions: {}

jobs:
  unit_test:
    uses: ./.github/workflows/unit_test.yml

  sca_scan:
    uses: ./.github/workflows/sca_scan.yml
    secrets: inherit
  
  code_scan:
    uses: ./.github/workflows/code_scan.yml
    secrets: inherit

  iac_scan:
    uses: ./.github/workflows/iac_scan.yml
    secrets: inherit
  
  container_scan:
    uses: ./.github/workflows/container_scan.yml
    secrets: inherit

  dependency_review:
    uses: ./.github/workflows/dependency_review.yml

  linter:
    permissions:
      contents: read
      statuses: write
      packages: read
    uses: ./.github/workflows/linting.yml
    secrets: inherit



