name: Unit Test

on:
  workflow_call:
   
jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
      - name: Install Snyk CLI
        run: npm install snyk -g
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }} 
        
      - name: Run tests
        run: npm test